/**
 * App color palette for light and dark mode. Use `getThemeColors()` from
 * `utils/themeColors.ts` rather than reading from this file directly.
 */

const tintColorLight = '#F94460';
const tintColorDark = '#F94460';

export const Colors = {
  light: {
    text: '#1A1A1A',
    background: '#FAFAFA',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    cardBackground: '#FFFFFF',
    surfaceBackground: '#F8F8F8',
    inputBackground: '#FFFFFF',
    headerBackground: '#FFFFFF',
    border: '#E5E5E5',
    inputBorder: '#E5E5E5',
    separator: 'rgba(0, 0, 0, 0.1)',
    secondaryText: '#6B7280',
    placeholder: '#7B7B8B',
    chevron: '#999999',
    link: '#306DD6',
    destructive: '#EF4444',
    buttonSecondaryBackground: '#ECECEC',
    buttonSecondaryBorder: '#D0D0D0',
    highlightBackground: '#F8FCFD',
    highlightBorder: '#E0F2F7',
    highlightIconBackground: '#E0F2F7',
    calendarAccent: tintColorLight,
    calendarDotDefault: tintColorLight,
  },
  dark: {
    text: '#FFFFFF',
    background: '#161622',
    tint: tintColorDark,
    icon: '#CDCDE0',
    tabIconDefault: '#CDCDE0',
    tabIconSelected: tintColorDark,
    cardBackground: '#1E1E2D',
    surfaceBackground: '#1E1E2D',
    inputBackground: '#1E1E2D',
    headerBackground: '#171615',
    border: '#3A3A4A',
    inputBorder: '#232533',
    separator: 'rgba(255, 255, 255, 0.1)',
    secondaryText: '#9CA3AF',
    placeholder: '#7B7B8B',
    chevron: '#999999',
    link: '#5B9BFF',
    destructive: '#EF4444',
    buttonSecondaryBackground: '#1E1E2D',
    buttonSecondaryBorder: '#3A3A4A',
    highlightBackground: '#1A2530',
    highlightBorder: '#2A3F4A',
    highlightIconBackground: '#2A3F4A',
    calendarAccent: tintColorDark,
    calendarDotDefault: tintColorDark,
  },
  semantic: {
    success: '#34C759',
    successDark: '#34C759',
    error: '#FF3B30',
    errorDark: '#FF3B30',
    info: '#007AFF',
    infoDark: '#0A84FF',
    neutral: '#8E8E93',
    neutralDark: '#8E8E93',
    placeholderLight: '#6B7280',
    placeholderDark: '#9CA3AF',
  },
};
